[tools]
bat = "latest"
chezmoi = "latest"
fzf = "latest"
lsd = "latest"
neovim = "latest"
node = "latest"
ripgrep = "latest"
fd = "latest"      # better find command
usage = "latest"   # for mise completion
